# Generated by Django 3.1.4 on 2021-03-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=128, unique=True)),
                ('c_agent', models.CharField(max_length=64)),
                ('c_logo', models.ImageField(upload_to='logo/%Y')),
                ('c_email', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=64, unique=True)),
                ('u_password', models.CharField(max_length=254)),
                ('u_name', models.CharField(max_length=128)),
                ('u_idcard', models.CharField(max_length=128)),
                ('u_email', models.CharField(max_length=128, unique=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'work_user',
            },
        ),
    ]
