# Generated by Django 3.1.4 on 2021-03-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
