# Generated by Django 3.1.4 on 2021-01-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=64, unique=True)),
                ('u_password', models.CharField(max_length=64)),
                ('u_sex', models.IntegerField(default=0)),
                ('u_phone', models.CharField(max_length=128)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('u_position', models.IntegerField(default=0)),
                ('u_icon', models.ImageField(upload_to='icon/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'work_user',
            },
        ),
    ]
