# Generated by Django 3.1.4 on 2021-03-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/%Y/%M/%D')),
                ('sex', models.BooleanField(default=0)),
                ('work_age', models.IntegerField(default=0)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('pic1', models.ImageField(upload_to='conclude/%y/%m/%d')),
                ('pic2', models.ImageField(upload_to='join/%y/%m/%d')),
                ('pic3', models.ImageField(upload_to='KPI/%y/%m%d')),
            ],
        ),
    ]
