# Generated by Django 3.1.4 on 2021-03-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='resume',
        ),
    ]
