# Generated by Django 3.1.4 on 2021-03-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210306_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='age',
            field=models.IntegerField(default=18, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pic1',
            field=models.ImageField(upload_to='conclude'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pic2',
            field=models.ImageField(upload_to='join'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pic3',
            field=models.ImageField(upload_to='KPI'),
        ),
    ]
