# Generated by Django 3.1.4 on 2021-03-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210306_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='position',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
