# Generated by Django 3.1.4 on 2021-03-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='KPI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='conclude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='join',
            field=models.IntegerField(default=0),
        ),
    ]
