# Generated by Django 3.1.4 on 2021-03-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210314_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='pic3',
            new_name='KPI_pic',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='pic1',
            new_name='conclude_pic',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='pic2',
            new_name='join_pic',
        ),
    ]
