# Generated by Django 3.1.4 on 2021-03-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210319_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='KPI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='conclude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='join',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
