# Generated by Django 3.1.4 on 2021-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20210319_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='temp_score',
            field=models.IntegerField(default=0),
        ),
    ]
